import { PROJECT_PERMISSION, PROJECT_ROLE_KEY } from '../../../shared/projects/constants'

export const BUILT_IN_PROJECT_ROLES = {
  [PROJECT_ROLE_KEY.ADMIN]: {
    permissions: Object.freeze(Object.values(PROJECT_PERMISSION)),
  },
  [PROJECT_ROLE_KEY.EDITOR]: {
    permissions: [
      PROJECT_PERMISSION.PROJECT_VIEW,
      PROJECT_PERMISSION.DOCUMENTS_VIEW,
      PROJECT_PERMISSION.DOCUMENTS_CREATE,
      PROJECT_PERMISSION.DOCUMENTS_UPDATE_DRAFT,
      PROJECT_PERMISSION.DOCUMENTS_PUBLISH,
      PROJECT_PERMISSION.DOCUMENTS_MOVE,
      PROJECT_PERMISSION.DOCUMENTS_ARCHIVE,
      PROJECT_PERMISSION.DOCUMENTS_RESTORE,
      PROJECT_PERMISSION.DOCUMENTS_VIEW_HISTORY,
      PROJECT_PERMISSION.MEMBERS_VIEW,
      PROJECT_PERMISSION.ROLES_VIEW,
    ],
  },
  [PROJECT_ROLE_KEY.VIEWER]: {
    permissions: [
      PROJECT_PERMISSION.PROJECT_VIEW,
      PROJECT_PERMISSION.DOCUMENTS_VIEW,
      PROJECT_PERMISSION.DOCUMENTS_VIEW_HISTORY,
    ],
  },
} as const
